babdev_pagerfanta:
  exceptions_strategy:
    # The exception strategy if requesting a page outside the available pages in a paginated list; valid options are "custom" or "to_http_not_found"
    out_of_range_page: custom

    # The exception strategy if the current page is not an allowed value in a paginated list; valid options are "custom" or "to_http_not_found"
    not_valid_current_page: custom
