# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  param_fetcher_listener: true
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: violations
  view:
    view_response_listener: true

  format_listener:
    rules:
      - { path: ^/, fallback_format: json, priorities: [json] }
  serializer:
    serialize_null: true
