nelmio_api_doc:
  documentation:
    info:
      title: Bilemo
      description: Your API for mobile phones!
      version: 1.0.0

    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT

    security:
      - Bearer: []

    paths:
      /api/login:
        post:
          tags:
            - \Login
          summary: Login into the api
          requestBody:
            content:
              application/json:
                schema:
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  type: object
          responses:
            "200":
              description: OK
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      token:
                        type: string
                      refresh_token:
                        type: string
            "401":
              description: Invalid credentials
            "400":
              description: Invalid Json
          security: []

      /api/token/refresh:
        post:
          tags:
            - \Login
          summary: Login into the api with refresh token
          requestBody:
            content:
              application/json:
                schema:
                  properties:
                    refresh_token:
                      type: string
                  type: object
          responses:
            "200":
              description: OK
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      token:
                        type: string
                      refresh_token:
                        type: string
            "401":
              description: Invalid Token
            "400":
              description: Invalid Json
          security: []

      /api/doc.json:
        get:
          tags:
            - \Documentation
          summary: Access to the API documentation in Json
          responses:
            "200":
              description: OK
          security: []

  areas:
    path_patterns: # an array of regexps
      - ^/api(?!/doc)
